### ISSUE TITLE
Build error : unknown tls.Config field 'GetCertificate

### ISSUE THREAD

**Issue by rinrynque** [twitchyliquid64/subnet#13]
Hello,
I'm getting an error when getting subnet :
```
> go get -u github.com/twitchyliquid64/subnet
# github.com/twitchyliquid64/subnet/subnet/conn
src/github.com/twitchyliquid64/subnet/subnet/conn/tls.go:68: unknown tls.Config field 'VerifyPeerCertificate' in struct literal
```
Found this but I don't have a clue how to fix it myself
https://github.com/strukturag/spreed-webrtc/issues/278

**Comment by twitchyliquid64** [comment]
Make sure you are using Go 1.8 or newer (that API was only introduced
later).

**Comment by rinrynque** [comment]
Thanks ! It was that indeed (debian repos are old)
