### ISSUE TITLE
how to revoke client cert (crl)?

### ISSUE THREAD

**Issue by kk44** [twitchyliquid64/subnet#5]

**Comment by twitchyliquid64** [comment]
My latest commit adds a CRL mechanism for blacklisting client certs on the server.

Launch the server with an additional parameter: `-crl <path_to_json_crl_file>`. You can make an empty CRL file with `echo "[]" > crl.json`.

To blacklist a cert, run subnet like this: 
```shell
./subnet -mode blacklist-cert -crl crl.json client.certPEM "Private key accidentally committed to github"
```

When launched with `-crl` the server will reload its blacklist from disk every 2 minutes.
